export var ERROR_CODES;
(function (ERROR_CODES) {
    ERROR_CODES["EMAIL_EXISTS"] = "EMAIL_EXISTS";
    ERROR_CODES["NO_ACCOUNT"] = "NO_ACCOUNT";
    ERROR_CODES["NOT_FOUND"] = "Not found";
    ERROR_CODES["WRONG_PASSWORD"] = "WRONG_PASSWORD";
})(ERROR_CODES || (ERROR_CODES = {}));
;
