export var STATUS_CODES;
(function (STATUS_CODES) {
    STATUS_CODES[STATUS_CODES["OK"] = 200] = "OK";
    STATUS_CODES[STATUS_CODES["CREATED"] = 201] = "CREATED";
    STATUS_CODES[STATUS_CODES["UNAUTHORIZED"] = 401] = "UNAUTHORIZED";
    STATUS_CODES[STATUS_CODES["NOT_FOUND"] = 404] = "NOT_FOUND";
    STATUS_CODES[STATUS_CODES["CONFLICT"] = 409] = "CONFLICT";
    STATUS_CODES[STATUS_CODES["SERVER_ERROR"] = 500] = "SERVER_ERROR";
})(STATUS_CODES || (STATUS_CODES = {}));
;
